# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5830ee1acf7c16bba195bcbddfbcc0883a9166e6efab4a03b87f9952c5d8c467a5af84c44c035554418068770718d677388ee322c22e0e8ecd9c767ccc08614

test:
  secret_key_base: 239704b6fa8975313535b0393e0c48d95a379d241e3be5f41401c87ef5844d2a18e972e98367d5d4a32ab80be2fd4634befc1735209d2d46cec7f24959e372d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
