production:
  solr:
    hostname: 127.0.0.1
    port: 8982
    log_level: WARNING
    path: /solr/development
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: 127.0.0.1
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: 127.0.0.1
    port: 8982
    log_level: WARNING
    path: /solr/development
    